@hostname = http://127.0.0.1
@port = 8888
@host = {{hostname}}:{{port}}
@contentType = application/json

### Send message to queue

POST {{host}}/messages/myqueue
content-type: {{contentType}}

{
  "user_id": "1",
  "platform": "My Platform",
  "type": "user",
  "intent": "my intent",
  "not_handled": false,
  "message": "my message"
}

### Queues list

GET {{host}}/queues
content-type: {{contentType}}

### Create queue

POST {{host}}/queues/myqueue2
content-type: {{contentType}}

### Delete queue

DELETE  {{host}}/queues/myqueue2
content-type: {{contentType}}

