FROM node:10.14.1-alpine

RUN yarn global add nodemon

WORKDIR /rsmq.chatbase.worker

COPY package*.json yarn.lock ./
RUN yarn install --production=true --ignore-optional

WORKDIR /rsmq.chatbase.worker/src

CMD [ "nodemon", "--signal", "SIGINT", "chatbase.worker.js" ]
